version: '3.8'
services:
  blog-api:
    build: ./api
    container_name: blog-api-c
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
  db:
    image: mongo:latest
    ports:
      - "3456:27017"
    volumes:
      - type: volume
        source: /app/blog/data
        target: /data/db