version: '3.8'
services:
  blog-api:
    build: ./api
    container_name: blog-api-c
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/blog/public:/app/public
  db:
    image: mongo:latest
    container_name: blog-db-c
    ports:
      - "3456:27017"
    volumes:
      - /app/blog/data:/data/db